name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        # mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        # mhausenblas/mkdocs-deploy-gh-pages@master to build with the mkdocs-material theme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # CUSTOM_DOMAIN: optionaldomain.com
          CONFIG_FILE: mkdocs.yml
          # The EXTRA_PACKAGES variable will be passed to the apk add command of Alpine Linux before running pip install
          EXTRA_PACKAGES: build-base libffi-dev
          # GITHUB_DOMAIN: github.myenterprise.com
          REQUIREMENTS: requirements.txt